format_strawberryfield.iiif_settings:
  type: config_object
  label: 'Archipelago IIIF Server configurations'
  mapping:
    pub_server_url:
      type: string
      label: 'Public IIIF server URL'
    int_server_url:
      type: string
      label: 'Internal IIIF server URL'

field.formatter.settings.strawberry_audio_formatter:
  type: mapping
  label: 'Specific config for strawberry_audio_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: string
    max_height:
      type: string
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    audio_type:
      type: string
    number_media:
      type: integer

field.formatter.settings.strawberry_image_formatter:
  type: mapping
  label: 'Specific Config for strawberry_image_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: string
    max_height:
      type: string
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    number_images:
      type: string
    image_type:
      type: string
    webannotations:
      type: boolean
    quality:
      type: string
    rotation:
      type: string
    image_link:
      type: boolean
field.formatter.settings.strawberry_media_formatter:
  type: mapping
  label: 'Specific Config for strawberry_media_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: string
    max_height:
      type: string
    webannotations:
      type: boolean
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    iiif_group:
      type: boolean
      label: 'Whether multiple media sources should use a single IIIF viewer or not.'
    thumbnails:
      type: boolean
      label: 'TNs?'
    number_images:
      type: integer
      label: 'Number of images'
field.formatter.settings.strawberry_3d_formatter:
  type: mapping
  label: 'Specific Config for strawberry_3d_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: string
    max_height:
      type: string
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    number_models:
      type: integer
      label: 'Number of 3D Models to load from JSON'

field.formatter.settings.strawberry_metadata_formatter:
  type: mapping
  label: 'Specific Config for strawberry_metadata_formatter using Twig'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: integer
    max_height:
      type: integer
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    label:
      type: string
    specs:
      type: string
    metadatadisplayentity_id:
      type: string
    metadatadisplayentity_uselabel:
      type: string
field.formatter.settings.strawberry_paged_formatter:
  type: mapping
  label: 'Specific Config for strawberry_paged_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    iiif_group:
      type: boolean
      label: 'Whether multiple media sources should use a single IIIF viewer or not.'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: string
    max_height:
      type: string
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    mediasource:
      type: string
    metadatadisplayentity_source:
      type: string
    manifesturl_source:
      type: string
field.formatter.settings.strawberry_pannellum_formatter:
  type: mapping
  label: 'Specific Config for strawberry_pannellum_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: string
    max_height:
      type: string
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    hotSpotDebug:
      type: boolean
    image_type:
      type: string
    json_key_hotspots:
      type: string
    json_key_settings:
      type: string
    json_key_multiscene:
      type: string
    panorama_type:
      type: integer
    quality:
      type: string
    rotation:
      type: string
    autoLoad:
      type: boolean
    number_images:
      type: integer
      label: "Number of Images"
field.formatter.settings.strawberry_video_formatter:
  type: mapping
  label: 'Specific Config for strawberry_video_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: string
    max_height:
      type: string
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    audio_type:
      type: string
    json_key_source_for_poster:
      type: string
    number_media:
      type: integer
    posterframe:
      type: string
field.formatter.settings.strawberry_pdf_formatter:
  type: mapping
  label: 'Specific Config for strawberry_pdf_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    max_width:
      type: string
      label: 'Max with for the Viewer. Can be either a % or just a number'
    max_height:
      type: string
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    number_documents:
      type: integer
      label: 'Number of PDF Documents to load'
    number_pages:
      type: integer
      label: 'Number of Pages to show per PDF'
    initial_page:
      type: integer
      label: 'First Page to display per PDF'
field.formatter.settings.strawberry_mirador_formatter:
  type: mapping
  label: 'Specific Config for strawberry_mirador_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    metadataexposeentity:
      type: string
      label: 'Machine name of the exposed Metadata Config Entity endpoint'
    mediasource:
      type: mapping
      label: 'Sources for IIIF URL'
      mapping:
        manifestnodelist:
          type: string
          label: 'If manifestnodelist is being used'
        metadataexposeentity:
          type: string
          label: 'If metadataexposeentity is being used'
        manifesturl:
          type: string
          label: 'If manifesturl is being used'
    main_mediasource:
      type: string
      label: 'Primary IIIF URL Source used'
    metadataexposeentity_source:
      type: string
      label: 'metadataexpose_entity machine name'
    manifestnodelist_json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing NODE ids or UUIDs from which to generate Manifest URLs'
    manifesturl_json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing IIIF Manifest URLs to display'
    max_width:
      type: string
      label: 'Max with for the Viewer. Can be either a % or just a number'
    max_height:
      type: string
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'

field.formatter.settings.strawberry_warc_formatter:
  type: mapping
  label: 'Specific Config for strawberry_warc_formatter'
  mapping:
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    navbar:
      type: boolean
      label: 'Whether to show or not the embeded widget browser nav bar'
    json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing file URIs to display'
    warcurl_json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing an URL of a warc to fetch'
    max_width:
      type: string
    max_height:
      type: string
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
    json_key_starting_url:
      type: string

# Multiple JSON type / View Mode Mappings
format_strawberryfield.viewmodemapping_settings:
  type: config_object
  label: 'Archipelago View Mode to JSON Type Key mapping Configurations'
  mapping:
    type_to_viewmode:
      type: sequence
      label: 'JSON type key to View Mode Mapping'
      sequence:
        type: format_strawberryfield.viewmodemapping_settings.mapping

format_strawberryfield.viewmodemapping_settings.mapping:
  type: mapping
  label: 'JSON Type Key/ View Mode pair'
  mapping:
    jsontype:
      type: string
      label: 'JSON Type Key'
    view_mode:
      type: string
      label: 'View mode'
    active:
      type: boolean
      label: 'Whether this Config pair is enabled or not'
    weight:
      type: integer
      label: 'Order in which this is evaluated'

field.formatter.settings.strawberry_map_formatter:
  type: mapping
  label: 'Specific Config for strawberry_map_formatter'
  mapping:
    json_key_source:
        type: string
        label: 'JSON or JMESPATH that conditions rendering. If empty will always render'
    iiif_base_url:
      type: string
      label: 'Custom Public IIIF Server URL'
    iiif_base_url_internal:
      type: string
      label: 'Custom internal IIIF Server URL'
    metadataexposeentity:
      type: string
      label: 'Machine name of the exposed Metadata Config Entity endpoint'
    mediasource:
      type: mapping
      label: 'Sources for GeoJSON URL'
      mapping:
        geojsonnodelist:
          type: string
          label: 'If geojsonnodelist is being used'
        metadataexposeentity:
          type: string
          label: 'If metadataexposeentity is being used'
        geojsonurl:
          type: string
          label: 'If geojsonurl is being used'
    main_mediasource:
      type: string
      label: 'Primary GeoJSON Source used'
    metadataexposeentity_source:
      type: string
      label: 'metadataexpose_entity machine name'
    geojsonnodelist_json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing NODE ids or UUIDs from which to generate GeoJSON URLs'
    geojsonurl_json_key_source:
      type: string
      label: 'Strawberryfield/JSON key containing GeoJSON URLs to display'
    max_width:
      type: string
      label: 'Max with for the Map. 0 to force 100% width'
    max_height:
      type: string
    initial_zoom:
      type: integer
      label: 'Initial Zoom for the Map'
    max_zoom:
      type: integer
      label: 'Max Zoom for the Map'
    min_zoom:
      type: integer
      label: 'Min Zoom for the Map'
    tilemap_url:
      type: string
      label: 'Tile Map URL'
    tilemap_attribution:
      type: string
      label: 'Tile Map Attribution String'
    use_iiif_globals:
      type: string
      label: 'Whether to use global IIIF settings or not.'
# Given any DS field plugin formatter key a type
ds.field_plugin.*:
  type: mapping
  mapping:
    formatter:
      type: field.formatter.settings.[%parent.%parent.formatter]
      label: "Formatter settings for a generic ds.field plugin"
